# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clGmmIheCl5wrqhUmsLyIAW1zsH7rF5f
"""

import pandas as pd
import random
from datetime import date, timedelta

# 1. Estructura de datos
campaigns = {
    'Loyalty First': ['Amazon ads', 'Facebook ads'],
    'Back to Basics': ['Linkedin ads', 'Google Display & Video 360'],
    'Win-Back Outreach': ['StackAdapt', 'Google organic'],
    'Elite Rewards Program': ['Direct Traffic', 'Facebook ads'],
    'Eco-Forward Initiative': ['Amazon ads', 'Google organic'],
    'Global Reach Outreach': ['Google ads', 'StackAdapt'],
    'Spark Frenzy': ['Facebook ads', 'Direct Traffic'],
    'Wonderland Drive': ['Google Display & Video 360', 'Amazon ads']
}

source_to_channel = {
    'StackAdapt': 'Programmatic',
    'Google Display & Video 360': 'Programmatic',
    'Google ads': 'Paid Search',
    'Amazon ads': 'Paid Search',
    'Facebook ads': 'Paid Social',
    'Linkedin ads': 'Paid Social',
    'Google organic': 'Organic',
    'Direct Traffic': 'Organic'
}

# 2. Rango de fechas (Todo 2023)
start_date = date(2023, 1, 1)
end_date = date(2023, 12, 31)
delta = end_date - start_date
dates = [start_date + timedelta(days=i) for i in range(delta.days + 1)]

data = []

# 3. Motor de generación con lógica "orgánica" de canales
for d in dates:
    active_campaigns = random.sample(list(campaigns.keys()), random.randint(5, 8))

    for camp in active_campaigns:
        sources = campaigns[camp]

        num_sources = random.choices([1, 2], weights=[30, 70])[0]
        if num_sources == 2 and len(sources) > 1:
            active_sources = sources
        else:
            active_sources = [random.choice(sources)]

        for src in active_sources:
            channel = source_to_channel[src]

            # --- LÓGICA POR CANAL ---

            if channel == 'Paid Search':
                # Tráfico de intención: Altas conversiones, CTR alto, 0 video
                spend = round(random.uniform(1000, 5000), 2)
                impressions = random.randint(10000, 50000)
                clicks = random.randint(1000, 5000)
                conversions = random.randint(50, 200)
                video_views = 0

            elif channel == 'Programmatic':
                # Banners masivos: Impresiones altísimas, CTR bajísimo, mucho video si aplica
                spend = round(random.uniform(1000, 5000), 2)
                impressions = random.randint(200000, 800000)
                clicks = random.randint(200, 800)
                conversions = random.randint(5, 20)
                video_views = random.randint(10000, 50000)

            elif channel == 'Paid Social':
                # El punto medio: Buen balance, fuerte enfoque en video
                spend = round(random.uniform(1000, 5000), 2)
                impressions = random.randint(50000, 150000)
                clicks = random.randint(500, 2500)
                conversions = random.randint(20, 100)
                video_views = random.randint(5000, 30000)

            elif channel == 'Organic':
                # Tráfico gratuito: 0 costo, alta fidelidad
                spend = 0.0
                impressions = random.randint(5000, 20000)
                clicks = random.randint(500, 2000)
                conversions = random.randint(30, 150)
                video_views = 0

            else:
                # Fallback de seguridad (no debería ocurrir con tu mapeo)
                spend, impressions, clicks, conversions, video_views = 0, 0, 0, 0, 0

            # Asegurarnos de que por azares matemáticos los clics no superen las impresiones
            clicks = min(clicks, impressions)
            conversions = min(conversions, clicks)

            # Agregamos la fila a nuestra lista de datos
            data.append([
                d.strftime("%Y-%m-%d"),
                channel,
                src,
                camp,
                spend,
                impressions,
                clicks,
                video_views,
                conversions
            ])

# 4. Exportar a CSV
df = pd.DataFrame(data, columns=['Date', 'Channel', 'Data Source', 'Campaign Name', 'Spend', 'Impressions', 'Clicks', 'Video Views', 'Conversions'])
df.to_csv("dashboard_dummy_data.csv", index=False)

print(f"¡Éxito! Se han generado {len(df)} filas con un comportamiento de negocio realista por canal.")

